##jeremy zucker
##7.20.2011
##globals.r

library('Rcplex')
suppressMessages(library('Matrix'))
options(stringsAsFactors=FALSE)

setwd('/msc/neurospora/FBA/farm')
source('check_ko.r'); source('check_fba.r')
source('check_rxn.r')
source('check_new_media.r'); source('changeNuts.r')
source('cut_mets.r'); source('cut_revs.r')
source('gapfind.r')
source('fba.r'); source('fba_dual.r'); source('fba_na.r')
source('subset_mat.r'); source('flux_of_met.r'); source('minFlux4met.r')
source('fva_fcns.r'); source('tight_ub_fcns.r')
source('read_fba.r')
source('subset_rxns.r')
source('trace_mets.r')
source('min_export.r')
source('min_met_adj.r')
source('min_pen.r')
source('parse_supp.r'); source('test_supp.r')
source('get_biomass_mass.r')
source('irrev2rev.r')
source('predict_biolog.r')
source('call_check_ko.r')
source('metab_dilute_s.r')
source('merge_DBs.r')
source('make_sink.r')
source('ncu2rxns.r')
source('probs4rxns.r')
source('thermo_fcns.r')
source('make_rxn_annot.r')
source('get_x0.r')
source('get_x0_simple.r')
source('get_x0_md.r')
source('which_col.r')
source('get_met_mat.r')
source('parse_smm.r')
source('get_imbalance.r')
source('x2beta.r')
source('named_vec.r')
source('sparse_mat_fcns.r')
source('get_md_constraints_3c.r')
source('run_get_md_constraints_3c.r')
source('named_vec.r')
source('get_dual_constraints.r')
source('biolog_confusion.r')
source('run_pred_biolog.r')
source('get_gene_supp_mat.r')
source('make_grid.r')
source('my_rectangle.r')
source('multiGeneKO.r')
source('sl_add_names.r')
source('make_grid.r')
source('my_rectangle.r')

Sys.setlocale("LC_ALL", "C")
